src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
 path('', views.index_page, name='index_name'), 
 path('signup/', views.signup_page, name='signup_name'),
 path('login/', views.login_page, name='login_name'),
 path('logout/', views.logout_page, name='logout_name'),
 path('profile/', views.profile_page, name='profile_name'),
 path('contact/', views.contact_page, name='contact_name'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', views.index, name='home'),
    path('about', views.about_page, name='about_name'),

    path('', include('main.urls', namespace='main')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
   msg_id = models.AutoField(primary_key=True)
   name = models.CharField(max_length=200)
   email = models.CharField(max_length=200)
   phone = models.CharField(max_length=70)
   message = models.TextField()

   # def __str__(self):
   #    return self.name

src/main/forms.py
from cProfile import label
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
   password2=forms.CharField(label='Confirm Password(again)', widget=forms.PasswordInput)
   	
   class Meta:
      model = User
      fields = ['username', 'first_name', 'last_name', 'email']
      labels = { 'email' : 'Email' }
      

src/main/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from .models import Contact

# index view function
def index_page(request):
#  return HttpResponse("Hello, world. ")
   return render(request, 'main/index.html')

# about view function
def about_page(request):
   return render(request, 'main/about.html')

# signup view function
def signup_page(request):
   if request.method == 'POST':
      fm = SignUpForm (request.POST)
      if fm.is_valid():
         messages.success(request, 'Account Created Successfully!!')
         fm.save()            
   else:
      fm = SignUpForm ()

   return render(request, 'main/signup.html', {'form':fm})

# login view function
def login_page(request):
   if request.method == 'POST':
      fm = AuthenticationForm(request=request, data=request.POST)
      if fm.is_valid():            
         uname = fm.cleaned_data['username']
         upass = fm.cleaned_data['password']
         user = authenticate( username=uname, password=upass)
         if user is not None:
            login(request, user)            
         return HttpResponseRedirect('/profile/')
   else:
      fm = AuthenticationForm()    
   return render(request, 'main/login.html', {'form':fm})

# logout view function
def logout_page(request):   
   return render(request, 'main/logout.html')

# profile view function
def profile_page(request):
   messages.success(request, 'You have logged in successfully!!')  
   return render(request, 'main/profile.html', {'name':request.user})

# contact view function
def contact_page(request):
   thank = False
   if request.method == "POST":
      name = request.POST.get('name', '')
      email = request.POST.get('email', '')
      phone = request.POST.get('phone', '')
      message = request.POST.get('message', '')
      contact = Contact(name=name, email=email, phone=phone, message=message)
      messages.success(request, 'Message sent Successfully!!')
      contact.save()
      thank = True
   return render(request, 'main/contact.html', {'thank': thank})

src/mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
   return HttpResponse("Hello World!")

# about view function
def about_page(request):
   return render(request, 'about.html')

src/main/templates/main/contact.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
   <div class="col-sm-6"><h4>Address</h4></div>
   <div class="col-sm-6">
      <div class="card mb-4 mt-4 ">
         <div class="card-header"><h4>Contact Us</h4></div>
         <div class="card-body">
            <form action="/contact/" method="POST">{% csrf_token %}
               <div class="mb-3">
                 <label for="name" class="form-label">Name</label>
                 <input type="text" class="form-control" name="name" placeholder="Your Name" class="validate">
               </div>
               <div class="mb-3">
                 <label for="email" class="form-label">Email address</label>
                 <input type="email" class="form-control" name="email" placeholder="name@example.com" class="validate">
               </div>
               <div class="mb-3">
                 <label for="phone" class="form-label">Conact No.</label>
                 <input type="tel" class="form-control" name="phone" placeholder="Your Contact No." class="validate">
               </div>
               <div class="mb-3">
                 <div class="mb-3">
                   <label for="message" class="form-label">Message</label>
                   <textarea class="form-control" name="message" rows="3" placeholder="Your Message"></textarea>
                 </div>
                 <div class="mb-3">
                   <button type="submit" class="btn btn-primary">Send</button>
                 </div>
             </form>
         </div>
       </div>
   </div>
   <!-- Message -->
 {% if messages %}
 {% for message in messages %}
 <strong {%  if message.tags %} class="{{message.tags}} text-warning" {% endif %} > {{message}}</strong>
 {%  endfor%}
 {%  endif %}
</div>


{% endblock %}

src/main/templates/main/index.html
{% extends 'base.html' %}

{% block body %}
<h1>Welcome to index page</h1>
{% endblock %}

src/main/templates/main/login.html
{% extends 'base.html' %}

{% block body %}
<div class="card mb-4 mt-4 w-50 m-auto">
   <div class="card-header"><h4>Login To Your Account</h4></div>
   <div class="card-body">
     <form action="" method="POST" novalidate>
       {% csrf_token %}
       <!-- error message -->
       {% if form.non_field_errors %}
       {% for error in  form.non_field_errors %}
       <p class="text-danger">{{error}}</p>
       {% endfor %}
       {% endif %}
    
      {% for fm in form %}
      {{fm.label_tag}}  {{fm }}  {{fm.errors|striptags}} <br><br>
      {% endfor %}
       <button type="submit" class="btn btn-primary">Login</button>
     </form>
   </div>
 </div>
 
{% endblock %}

src/main/templates/main/logout.html
{% extends 'base.html' %}

{% block body %}

<h4>You have successfully logged out. 
<a href="{% url 'main:login_name' %}">Log back in here</a>
</h4>
{% endblock %}

src/main/templates/main/profile.html
{% extends 'base.html' %}

{% block body %}
<!-- Message -->

<h5>Welcome {{name}}, 
   {% if messages %}
{% for message in messages %}
   {{message}}
{%  endfor%}
{%  endif %}
</h5>
{% endblock %}

src/main/templates/main/signup.html
{% extends 'base.html' %}

{% block body %}
<div class="card mb-4 mt-4 w-50 m-auto">
   <div class="card-header"><h4>Create An Account</h4></div>
   <div class="card-body">
     <form action="" method="POST" novalidate>
       {% csrf_token %}
    <!-- error message -->
    {% if form.non_field_errors %}
    {% for error in  form.non_field_errors %}
    <p class="text-danger">{{error}}</p>
    {% endfor %}
    {% endif %}
      {% for fm in form %}
      {{fm.label_tag}}  {{fm }}  {{fm.errors|striptags}} <br><br>
      {% endfor %}
       <button type="submit" class="btn btn-primary">Create Account</button>
     </form>
   </div>
 </div>
 <!-- Message -->
 {% if messages %}
 {% for message in messages %}
 <strong {%  if message.tags %} class="{{message.tags}} text-warning" {% endif %} > {{message}}</strong>
 {%  endfor%}
 {%  endif %}

 
{% endblock %}

src/templates/about.html
{% extends 'base.html' %}

{% block body %}
<h1> About Page</h1>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{% block title %}{% endblock %}</title>
   <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
   <link rel="stylesheet" href="{% static 'css/core.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <!-- font family -->
   <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Oswald&display=swap" rel="stylesheet"
</head>
<body>
   {% include 'navbar.html' %}
   <div class="container">
   
   
   {% block body %}{% endblock %}
 
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/fontawesome.js' %}"></script>
<!-- <script src="https://kit.fontawesome.com/d297b7afee.js" crossorigin="anonymous"></script> -->


</div>
</body>
</html>

src/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">   
   
   <link rel="stylesheet" href="{% static 'css/nav.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
  <nav class="container-fluid navbar active px-5">
    <div class="logo">
      <h1 class="text-white">MyProject</h1>
    </div>
    <ul class="nav-links">
      <li><a href="{% url 'main:index_name' %}">Home</a></li>
      <li><a href="{% url 'about_name' %}">About</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'main:logout_name' %}">Log out</a></li> 
      {% else %}     
      <li><a href="{% url 'main:signup_name' %}">Sign Up</a></li>
      <li><a href="{% url 'main:login_name' %}">Log In</a></li>
      {% endif %}      
      <li><a href="{% url 'main:contact_name' %}">Contact</a></li>
    </ul>
    <div class="burger">
      <div class="line1"></div>
      <div class="line2"></div>
      <div class="line3"></div>
    </div>
  </nav>     
 
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/jquery.js' %}"></script>

</body>
<script>
  // alert("testing");
  const navSlide = () => {
    const nav = document.querySelector(" .navbar");
    const burgerToggle = document.querySelector(".burger");
    // nav-links toggle
    burgerToggle.addEventListener("click", () => {
      nav.classList.toggle("active");

      // burger animation
      burgerToggle.classList.toggle("toggle");
    });
  };
  navSlide();
</script>
</html>